version: '3.9'

services:
  db:
    container_name: 'desafio-classroom-db'
    image: postgres
    volumes:
      - storage_db:/var/lib/postgres/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: classroom
      POSTGRES_DB: classroom

volumes:
  storage_db:
